
spring:
      profiles:
              active: dev                                  #配置激活的profiles 
      mvc:
              static-path-pattern: classpath:/static/**
              
              throw-exception-if-no-handler-found: true    #404直接抛出异常，而不是跳转到/error
      resources:
              
              addMappings: false                           #阻止SpringBoot为工程的资源文件建立映射
 
          
      http: 
              encoding: 
                       force: true
                       charset: UTF-8                      # Charset of HTTP requests and responses
                       enabled: true                       # Enable http encoding support

                       
                        
 
 
#profiles  dev 
---
spring:
      profiles: dev
      datasource: 
                url: jdbc:mysql://127.0.0.1:3306/test
                driver-class-name: com.mysql.jdbc.Driver  
                username: root
                password: 
      redis: 
                database: 0                                 #指定数据库
                host: 192.168.5.227
                port: 6379
                password: 
                pool: 
                         max-active: 8                       #最大连接数
                         max-wait: -1                        #连接池最大阻塞等待时间  -1表示没有限制
                         max-idle: 8                         #最大空闲连接
                         min-idle: 0                         #最小空闲连接
                         timeout: 5000                       #连接超时时间  ms

mybatis: 
      configLocation: classpath:mybatis/mybatis-config.xml
      mapperLocations: classpath:mybatis/mapper/*.xml   
      
server:
      tomcat:
              basedir:   ./
      port: 8080
      
#profiles  test  
---

                
#profiles prod     
---

