
spring:
      profiles:
              active: dev                                  #配置激活的profiles 
      mvc:
              static-path-pattern: classpath:/static/**
              
              throw-exception-if-no-handler-found: true    #404直接抛出异常，而不是跳转到/error
      resources:
              
              addMappings: false                           #阻止SpringBoot为工程的资源文件建立映射
 
          
           
redis:                                                     #默认redis配置
  host: 192.168.5.110 
  port: 6379
 
 
#profiles  dev 
---
spring:
      profiles: dev
      
redis: 
  host: 192.168.5.227 
  port: 6379
  
server:
      tomcat:
              basedir:   ./

#profiles  test  
---
spring:
      profiles: dev
      
redis: 
  host: 192.168.5.227 
  port: 6379
  
server:
      tomcat:
              basedir:   
                
#profiles prod     
---
spring:
      profiles: prod
      
redis: 
  host: 192.168.5.229 
  port: 6379
  
server:
      tomcat:
              basedir:   /home/xxx